### ISSUE TITLE
[BUG] I cannot get my boat from lsmc.

### ISSUE THREAD

**Issue by Iwear0000FF** [xXJamieXx/paradox-bugs#251]
**Your Discord Name**
Play3r0000FF#9352

**Describe the bug**
[I bought a dingy to dive with a friend and let him drive. when we stopped at the docks in paleto he for some unkown reason decided to put my boat in his garage.  it then vanished. I then found it down at the middle lsmc dock but cant take it out of the garage at all. I have tried flying out and it doesnt help.]

**To Reproduce**
[Steps to reproduce the bug]
1. Buy a new boat.
2. Have some one else dock your new boat you've never docked
3.  try to take it out of middle lsmc garage

**Expected behavior**
[I expected it would be able to be clicked on in the depot and it would spawn.]

**Screenshots**
https://i.imgur.com/6jSSfmE.jpeg

**Logs**
[Add your FiveM logs]

https://user-images.githubusercontent.com/100473322/155843181-33352bfe-989a-4b05-87ad-4485ea9e7171.mp4

**Comment by JnKTechstuff** [comment]
should be fixed now

**Comment by Iwear0000FF** [comment]
I still cannot retrieve my Boat. but now it does say my boat isnt in that boat house. ive checked all others and this is the only one it even shows up in tho

https://user-images.githubusercontent.com/100473322/155988531-d4116ac2-78d4-46dc-8edc-94a420ee40e9.mp4

![FiveM_b2545_GTAProcess_ICis353z3w](https://user-images.githubusercontent.com/100473322/155988720-1bca6450-fe07-4a6c-a7c5-f9b796419058.jpg)
.
