### ISSUE TITLE
[BUG] Incorrect Trucking Job Distances

### ISSUE THREAD

**Issue by TheAzian47** [xXJamieXx/paradox-bugs#342]
**Your Discord Name**
TheAzian47#2758

**Describe the bug**
So if you choose a job that is either 1 or 2 miles in length, instead of giving you that length, it will give you a route longer than advertised. For example, I had a 1 mile trucking job. When I selected it, it gave me a 4 mile job instead.

**To Reproduce**
[Steps to reproduce the bug]
1. Go to the trucking depot
2. Pick a 1 or 2 mile job
3. 

**Expected behavior**
either make the trip lengths more accurate

**Screenshots**

![Screenshot 2022-03-26 224111](https://user-images.githubusercontent.com/98672976/160268490-0ac73bdc-bd05-4510-8c04-1b0cf90cc09e.png)
![Screenshot 2022-03-26 224159](https://user-images.githubusercontent.com/98672976/160268493-16dd76b3-93b7-42da-8527-5b0df00a8d89.png)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
None of the deliveries are that short in distance they are all set to be fairly long distance. I will look into why its showing a shorter distance.

**Comment by xXJamieXx** [comment]
Fixed next restart.

**Comment by jibbersh** [comment]
![image](https://user-images.githubusercontent.com/96938099/160318615-4f3679fe-bf4d-4384-9d6d-1b22c0be546c.png)
This is still an issue after restart.

**Comment by xXJamieXx** [comment]
Jeez what the actual... Ok I'll look into this more...

**Comment by xXJamieXx** [comment]
This was fixed.
