### ISSUE TITLE
PD Gun Loaded bullets disappear

### ISSUE THREAD

**Issue by serpenstream64** [xXJamieXx/paradox-bugs#410]
**Your Discord Name**
serpentstream#9989

**Describe the bug**
When I load my gun with bullets it shows 12/12 for bullets. If i put my gun away then pull it back out it no longer has the bullets in it.

**To Reproduce**
[Steps to reproduce the bug]
1. Load Gun
2. Put Gun Away
3. Pull Gun Back out.

**Expected behavior**
Gun Remains loaded

**Screenshots**
Video of the issue https://www.youtube.com/watch?v=kMWt4EbbAbc

**Logs**
https://i.imgur.com/VUjvn7Q.png
[CitizenFX_log_2022-04-20T005933.log](https://github.com/xXJamieXx/paradox-bugs/files/8517479/CitizenFX_log_2022-04-20T005933.log)

**Comment by JnKTechstuff** [comment]
Does this happen all the time?
Is it every gun?

**Comment by iCLassYx** [comment]
Also happened with me and my sig. Loaded it with ammo, put it my pockets, took it out, weapon was showing 0 ammo. Did not test it on any other weapons.

**Comment by CorFinn** [comment]
Another victim here. I simply pulled out my Sig, and all bullets disappeared. Checked F8. There was nothing there of import.

**Comment by TurboDummi** [comment]
Also just happened to me right now with my Glock, had 61 rounds when I checked it in my pockets but when I pulled it out it was there was nothing in the magazine or chamber and there was no reserve ammo

**Comment by JnKTechstuff** [comment]
Should be fixed next restart

**Comment by pulsevr34** [comment]
Still happening after restart.

https://user-images.githubusercontent.com/97071437/164333100-49adf335-cdf5-40f5-a96b-b7c459cd4a69.mp4
